version: "3.2"
services: 
  cliente:
    build: ./simple-client
    ports:
      - 80:80

  servidor:
    build: ./servidor
    ports:
      - 3000:3000

  fake-consume:
    build: ./fake-consumer
    depends_on: 
      - servidor

  user-service:
    build: ./user-service
    volumes: 
      - ./user-service/credentials.json:/app/credentials.json

  sensor-service:
    build: ./sensor-service
    volumes: 
      - ./user-service/credentials.json:/app/credentials.json
