version: "3.2"
services: 

  nginx:
    image: nginx
    volumes: 
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80

  cliente:
    build: ./simple-client


  user-service:
    build: ./user-service
    volumes: 
      - ./user-service/credentials.json:/app/credentials.json

  sensor-service:
    build: ./sensor-service
    volumes: 
      - ./user-service/credentials.json:/app/credentials.json
