version: "3.2"
services: 
  cliente:
    build: ./simple-client
    ports:
      - 80:80

  servidor:
    build: ./servidor
    ports:
      - 3000:3000

  fake-consume:
    build: ./fake-consumer
    depends_on: 
      - servidor

